[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"


[project]
name = "ehc-sn"
description = "Sequential Navigation (SN) for the Entorhinal–Hippocampal circuit (EHC)"
authors = [{ name = "Borja Esteban", email = "boressan@outlook.com" }]
license = { text = "Apache License 2.0" }
keywords = ["Sequential Navigation", "Entorhinal–Hippocampal circuit"]
readme = "README.md"
dynamic = ["version", "dependencies"]

[project.optional-dependencies]
test = ["pytest ~= 8.3.0"]


[tool.setuptools.dynamic]
version = { file = "VERSION" }
dependencies = { file = "requirements.txt" }


[project.urls]
homepage = "https://github.com/BorjaEst/ehc-sn"
documentation = "https://github.com/BorjaEst/ehc-sn"
repository = "https://github.com/BorjaEst/ehc-sn"
changelog = "https://github.com/BorjaEst/ehc-sn/blob/main/CHANGELOG.md"
issue_tracker = "https://github.com/BorjaEst/ehc-sn/issues"
source = "https://github.com/BorjaEst/ehc-sn"


[tool.pylint.main]
disable = ["non-ascii-name", "invalid-name"]


[tool.mypy]
plugins = "numpy.typing.mypy_plugin"
ignore_missing_imports = true

[tool.black]
line-length = 88
