[tool.poetry]
name = "ehc-sn"
version = "0.1.0"
description = ""
authors = ["Borja Esteban <boressan@outlook.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
numpy = "^2.1.3"


[tool.poetry.group.dev.dependencies]
pytest = "^8.3.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.pylint.main]
disable = ["non-ascii-name", "invalid-name"]


[tool.mypy]
plugins = "numpy.typing.mypy_plugin"

[tool.black]
line-length = 100
