[tool.poetry]
name = "ehc-sn"
version = "0.1.0"
description = ""
authors = ["Borja Esteban <boressan@outlook.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
torch = "^2.5.1"
torchvision = "^0.20.1"
torchaudio = "^2.5.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
