# Configuration file for the Sphinx documentation builder.

project = 'ehc-sn'
copyright = '2023, EHC Research Team'
author = 'EHC Research Team'

# The full version, including alpha/beta/rc tags
release = '0.1.0'

# Add any Sphinx extension module names here
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.viewcode',
    'sphinx.ext.napoleon',
    'sphinx.ext.mathjax',
]

# Add any paths that contain templates here
templates_path = ['_templates']

# The language for content autogenerated by Sphinx
language = 'en'

# List of patterns to exclude from source files
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

# The theme to use for HTML and HTML Help pages
html_theme = 'sphinx_rtd_theme'

# Add any paths that contain custom static files
html_static_path = ['_static']

# Napoleon settings
napoleon_google_docstring = False
napoleon_numpy_docstring = True
napoleon_use_param = False
napoleon_use_ivar = True

# AutoDoc settings
autodoc_member_order = 'bysource'
autodoc_typehints = 'description'

# Path setup for source code
import os
import sys
sys.path.insert(0, os.path.abspath('../src'))
